client/Geek.Web/Models/ErrorViewModel.cs
namespace Geek.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

client/Geek.Web/Controllers/HomeController.cs
using Geek.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Geek.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

client/Geek.Web/Controllers/ProdutoController.cs
using Geek.Web.Domain.Interface;
using Geek.Web.Domain.Model;
using Geek.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Geek.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoService _produtoService;

        public ProdutoController(IProdutoService produtoService)
        {
            _produtoService = produtoService;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _produtoService.Query();
            return View(products);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Post(ProdutoModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _produtoService.Post(model);

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Update(Guid id)
        {
            var model = await _produtoService.Get(id);

            if (model == null) 
                return NotFound();
                
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(ProdutoModel model)
        {
            if (ModelState.IsValid)
            {
                await _produtoService.Put(model);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var model = await _produtoService.Get(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ProdutoModel model)
        {
            await _produtoService.Delete(model.IdProduto);
            return RedirectToAction(nameof(Index));
        }
    }
}

client/Geek.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

client/Geek.Web/Views/Produto/Create.cshtml
@model Geek.Web.Domain.Model.ProdutoModel

<form asp-action="Post">
    <br />
    <div class="container border p-3">

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Nome" class="control-label pt-2" style="font-size=20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger" />
            </div>
            <div class="col-2">
                <label asp-for="NomeCategoria" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="NomeCategoria" class="form-control" />
                <span asp-validation-for="NomeCategoria" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="Descricao" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Descricao" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="ImageURL" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="Preco" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Cancelar</a>
            </div>

            <div class="col-5">
                <input type="submit" value="SALVAR" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial">
    }

client/Geek.Web/Views/Produto/Delete.cshtml
@model Geek.Web.Domain.Model.ProdutoModel

<form asp-action="Delete">
    <input asp-for="IdProduto" hidden>
    <br />
    <div class="container border p-3">
        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Nome" class="control-label pt-2" style="font-size=20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Nome" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label asp-for="NomeCategoria" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="NomeCategoria" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label asp-for="Descricao" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Descricao" disabled class="form-control" rows="5"></textarea>
            </div>
            <div class="col-2">
                <label asp-for="ImageURL" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageURL" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label asp-for="Preco" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Preco" disabled class="form-control" />
            </div>

            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Cancelar</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial">
    }

client/Geek.Web/Views/Produto/Index.cshtml
@model IEnumerable<Geek.Web.Domain.Model.ProdutoModel>

<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            @*<h1 class="text-primary">Produto</h1>*@
        </div>
        <div class="col text-end pt-1">
            <a asp-action="Create" class="btn btn-outline-info">
                <i class="fas fa-plus"></i> Novo
            </a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Preço</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Nome</td>
                    <td>@item.NomeCategoria</td>
                    <td>@((item.Preco).ToString("c"))</td>
                    <td>
                        <a asp-action="Update" class="btn btn-success" asp-route-id="@item.IdProduto">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.IdProduto">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

client/Geek.Web/Views/Produto/Update.cshtml
@model Geek.Web.Domain.Model.ProdutoModel

<form asp-action="Update">
    <input asp-for="IdProduto" hidden>
    <br />
    <div class="container border p-3">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Nome" class="control-label pt-2" style="font-size=20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger" />
            </div>
            <div class="col-2">
                <label asp-for="NomeCategoria" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="NomeCategoria" class="form-control" />
                <span asp-validation-for="NomeCategoria" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="Descricao" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Descricao" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="ImageURL" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="Preco" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Cancelar</a>
            </div>

            <div class="col-5">
                <input type="submit" value="SALVAR" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial">
    }

client/Geek.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Geek</title>
    <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon">
    <link rel="icon" href="/images/favicon.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img width="185px" src="/images/geek_shopping.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Geek.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>